### ISSUE TITLE
Changes in radio.net

### ISSUE THREAD

**Issue by MiKiL75** [plintx/mopidy-radionet#3]
Hi there, just wanted to inform that radio.net has made some changes in the website.
They have removed login function. - [radio.net Help Center - Why can't I log in?](https://radio.zendesk.com/hc/en-us/articles/225023848-Why-can-t-I-log-in-)
And now all the favorites are stored in browser local storage.

**Comment by hgblu-sammosna** [comment]
+1

**Comment by mjh-source** [comment]
Does this mean it's not possible to use the extension? When I run it, I just get an empty list. I presume this is meant to show saved radio stations that are accessed when logging in.

**Comment by kingosticks** [comment]
What about searching? There looks to be code to handle searching functionality.

**Comment by mjh-source** [comment]
I get this when trying to search. 

Sep 15 18:56:08 koro mopidy[577]: ERROR    [RadioNetBackend-3] mopidy_radionet.radionet Radio.net: Failed to connect https://radio.net/ retrying on next browse.
Sep 15 18:56:08 koro mopidy[577]: ERROR    [RadioNetBackend-3] mopidy_radionet.radionet Radio.net: Search error <!doctype html><html lang="en"><head><title>HTTP Status 401 – Unauthorized</t

**Comment by plintx** [comment]
Hi, sorry for the late reply. I haven't used it for a long time, now I'm working on fixing this extension.

**Comment by plintx** [comment]
Hello again, please check out the newer version: https://pypi.org/project/Mopidy-RadioNet/

**Comment by MiKiL75** [comment]
Installed v0.2.1 and it works great.
Thank you for fixing things.
